### ISSUE TITLE
v1 launch checklist

### ISSUE THREAD

**Issue by meetar** [polygon-city/polygon-city-app#120]
- [ ] finalize v1 conversion process
- [ ] finalize v1 upload process
- [ ] convert/upload v1 citygml data
- [ ] collect/upload some high-rez buildings
- [ ] write TOS
- [ ] finalize licensing details
- [ ] write v1 use cases
- [ ] test against v1 use cases

Notes:

- v1 conversion and upload processes are batched and local - v2 may be backgrounded.
- v1 citygml data will be Berlin and possibly a few other cities, depending on tests
- v1 use cases will be basic uploading, navigation, and downloading

**Comment by robhawkes** [comment]
I've just merged #125, which adds support for multiple licences (though CC0 is default). Batched uploads can specify whether they are CC-BY or CC0 to override the default.
